MODEL:
  TYPE: smt
  NAME: cifar100_base_224_1k
  DROP_PATH_RATE: 0.3
  SMT:
    EMBED_DIMS: [64, 128, 256, 512]
    CA_NUM_HEADS: [4, 4, 4, -1]
    SA_NUM_HEADS: [-1, -1, 8, 16]
    MLP_RATIOS: [8, 6, 4, 2]
    QKV_BIAS: True
    DEPTHS: [ 4, 6, 28, 2]
    CA_ATTENTIONS: [ 1, 1, 1, 0 ]
    HEAD_CONV: 7
    EXPAND_RATIO: 2
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 0.05
  BASE_LR: 1e-05
  WARMUP_LR: 1e-08
  MIN_LR: 1e-07
DATA:
  BATCH_SIZE: 64
  IMG_SIZE: 224
  DATASET: cifar100
